name: Check version

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  check_versions:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Check versions in notebooks
      run: |
        for file in *.ipynb; do
            echo "Checking ${file}";
            if ! ./tests/check_versions.py "${file}"; then
                echo "::error file=${file},title=Error";
                exit 1;
            fi
        done

